package exception;
import java.util.Scanner;
public class ExceptionHandling {
	public static void main(String[] args) {
		Scanner scanner = new Scanner(System.in);
		        
		        try {
		            System.out.print("Enter a number: ");
		            int num1 = scanner.nextInt();
		            
		            System.out.print("Enter another number: ");
		            int num2 = scanner.nextInt();
		            
		            int result = divide(num1, num2);
		            
		            System.out.println("Result: " + result);
		        } catch (ArithmeticException e) {
		            System.out.println("Error: " + e.getMessage());
		        } catch (Exception e) {
		            System.out.println("Error: " + e.getMessage());
		        } finally {
		            scanner.close();
		        }
		    }
		    
		    public static int divide(int num1, int num2) throws ArithmeticException {
		        if (num2 == 0) {
		            throw new ArithmeticException("Cannot divide by zero");
		        }
		        
		        return num1 / num2;

			}

		}